spring:
  config:
    import: application.yml
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariPool
      auto-commit: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        connection:
          isolation: READ_COMMITTED
        jdbc:
          lob:
            non_contextual_creation: true

app:
  secret-key: ${APP_SECRET_KEY}
